name: 同步 OpenWrt packages

on: [push]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v1
    
    - name: 初始化Git
      env:
        ACTION_DEPLOY_KEY: ${{ secrets.ID_RSA }}
      run: |
        mkdir -p ~/.ssh
        git config --global user.email "76885266@qq.com"
        git config --global user.name "Ouiae"
        echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan gitee.com >> ~/.ssh/known_hosts
    
    - name: 拉取Openwrt packages文件
      run: git clone https://git.openwrt.org/feed/packages.git openwrt_packages
    
    - name: 拉取Gitt packages项目
      run: git clone git@gitee.com:ouiae/packages.git
    
    - name: 处理官方packages文件
      run: |
        cd openwrt_packages
        rm -rf .git LICENSE
    
    - name: 更新packages文件
      run: cp -rdf openwrt_packages/* packages/
    
    - name: 同步Gitt文件
      run: |
        cd packages
        git add .
        git commit -m "Update File"
        git push
