name: 同步 OpenWrt

on: [push]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v1
    
    - name: 初始化Git
      env:
        ACTION_DEPLOY_KEY: ${{ secrets.ID_RSA }}
      run: |
        mkdir -p ~/.ssh
        git config --global user.email "76885266@qq.com"
        git config --global user.name "Ouiae"
        echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan gitee.com >> ~/.ssh/known_hosts
    
    - name: 拉取Openwrt luci文件
      run: |
        git clone https://git.openwrt.org/project/luci.git openwrt_luci
        git clone https://git.openwrt.org/feed/telephony.git openwrt_telephony
    
    - name: 拉取Gitt luci项目
      run: |
        git clone git@gitee.com:ouiae/luci.git
        git clone git@gitee.com:ouiae/telephony.git
    
    - name: 处理官方luci文件
      run: |
        rm -rf openwrt_luci/.git openwrt_luci/LICENSE
        rm -rf openwrt_telephony/.git openwrt_telephony/LICENSE
    
    - name: 更新luci文件
      run: |
        cp -rdf openwrt_luci/* luci/
        cp -rdf openwrt_telephony/* telephony/
    
    - name: 同步Gitt文件
      run: |
        cd luci
        git add .
        git commit -m "Update File"
        git push
        cd ..
        cd telephony
        git add .
        git commit -m "Update File"
        git push
